# -*- coding: utf-8 -*-
"""GenAI_Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZZLBI9CmijtX4VIPS5NrHxxC93wYnow
"""

correct_username = "admin"
correct_password = "1234"

username = input("Enter Your Username Here: ")
password = input("Enter Your Password Here: ")

#User Login Credendial Check
if username == correct_username and password == correct_password:
  print("Login Successful!!!")
else:
  print("Invalid Username or Password.")

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print("Total Students:", len(marks))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

#Calculate pass and fail counts
for mark in marks:
    if mark >= 50:
        print(f"{mark} = Pass")
        pass_count += 1
    else:
        print(f"{mark} = Fail")
        fail_count += 1

#Print counts
print("Total Students:", len(marks))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)

def clean_names(names):
    cleaned_list = []

#Clean data
    for name in names:
        cleaned_name = name.strip().lower()
        cleaned_list.append(cleaned_name)

    return cleaned_list


names = ["Alice ", " bob", "CHARLIE"]

cleaned_names = clean_names(names)

#Print cleaned data
print("Cleaned Names:", cleaned_names)

def analyze_messages(messages):
  # find length of messages
    for message in messages:
        length = len(message)
        print(f"Message: '{message}'")
        print("Length:", length)

# print meassages and thier lengths
        if length > 10:
            print("Status: Message is longer than 10 characters.")
        else:
            print("Status: Normal size Message.")

        print("-" * 30)

#feed list
messages = ["Hi", "Welcome to the platform", "OK"]

analyze_messages(messages)

def count_errors(logs):
    error_count = 0
# error count
    for log in logs:
        if log == "ERROR":
            error_count += 1

    return error_count


logs = ["INFO", "ERROR", "WARNING", "ERROR"]

total_errors = count_error(logs)

#print error count
print("Total ERROR entries:", total_errors)

def count_errors(logs):
    error_count = 0

    for log in logs:
        if log == "ERROR":
            error_count += 1

    return error_count


logs = ["INFO", "ERROR", "WARNING", "ERROR"]

total_errors = count_errors(logs)

print("Total ERROR entries:", total_errors)

def count_errors(logs):
    error_count = 0
#error count
    for log in logs:
        if log == "ERROR":
            error_count += 1

    return error_count


logs = ["INFO", "ERROR", "WARNING", "ERROR", "ERROR", "Error"]

total_errors = count_errors(logs)

#print error count
print("Total ERROR entries:", total_errors)

